### ISSUE TITLE
Integrate all heads into master (or delete them otherwise)

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/curc-bench#111]
These are the branches and other HEADs that I currently have and do not appear to be merged into master. These should be merged or discarded.

* PR #101 (make sure this gets closed out)
* https://github.com/ResearchComputing/curc-bench/tree/aaron-pr
* https://github.com/ResearchComputing/curc-bench/tree/aaron-v0.3.0
* https://github.com/ResearchComputing/curc-bench/tree/aaron-master

**Comment by AaronTHolt** [comment]
PR #101 is closed out. Extra heads have been deleted (their content was already integrated into master).
