### ISSUE TITLE
Update and/or enable a procedure to install and run curc-bench as an arbitrary user

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/curc-bench#126]
This is a good start...

https://oitkb.colorado.edu/pages/viewpage.action?pageId=11580805

...but

1. it shouldn't have to be run as a certain user
2. it should start with an installation procedure

**Comment by AaronTHolt** [comment]
Progress has been made by installing in rcops projects dir so anyone on Summit can use with a module load. Curc-bench still requires 'python setup.py develop', and should be modified so that you can install it like a normal python package.
