### ISSUE TITLE
Replace subprocess with pyslurm in bench.reserve

### ISSUE THREAD

**Issue by AaronTHolt** [ResearchComputing/curc-bench#57]

**Comment by anderbubble** [comment]
This can't work right now, because pyslurm won't let us name the reservation. A pyslurm dev has indicated that he'll work on it.

**Comment by anderbubble** [comment]
Mark Robers from the pyslurm dev team indicates that we should be able to create named reservations with the latest development in master.

**Comment by AaronTHolt** [comment]
Closing since we're moving away from PySlurm.
